app/javascript/js/board.js, app/views/admin/job_applications/_job_application_head.html.haml, app/views/admin/job_offers/show.html.haml, db/seeds.rb
+ le drag and drop est désactivé
=> Protéger le bouton "Changer d'état" pour les candidatures suivant les droits de l'utilisateur courant #55

app/views/admin/settings/administrators/index.html.haml
J'ai inversé la condition et la valeur
=> correction du administrator.last_sign_in_at.present? hotfix #48

app/controllers/admin/job_applications_controller.rb, app/views/admin/job_applications/_job_application_overview.html.haml, app/views/admin/job_applications/_other_job_applications.html.haml, config/locales/fr.yml, db/seeds.rb, spec/views/admin/job_applications/show.html.haml_spec.rb
+ : Quand il n'y en a pas la "fenêtre" Autres candidatures de ce candidat ne s'affiche pas.
=> Affichage des autres candidature d'un candidat #122

app/views/admin/job_applications/_filters.html.haml, app/views/job_offers/_filters.html.haml, config/locales/devise.fr.yml, config/locales/fr.yml, config/locales/simple_form.fr.yml
dans la règle :
Remplacer "Métier/Profession/Catégorie de métier" par "Domaines professionnels"
je n'ai pas trouvé "Profession"
=> Modification des fichiers de traduction #132

app/models/administrator.rb
This reverts commit d542f1f7e46995718367ff5bc06ffec8176fae62.
=> Revert "quick fix auth method"

app/controllers/admin/job_offers_controller.rb
https://github.com/betagouv/civilsdeladefense/issues/441
=> fix: handle case when job_offer has errors

app/models/ability.rb, spec/controllers/admin/job_applications_controller_spec.rb, spec/support/controller_macros.rb
=> feat: allow administrator to manage application if concerned

app/controllers/admin/job_offers_controller.rb, spec/controllers/admin/job_offers_controller_spec.rb
=> fix: search user with downcase email

app/models/job_application.rb
=> fix: handle job_application after user delete his account

Gemfile, Gemfile.lock, app/javascript/css/_france-connect.scss, app/views/devise/shared/_france_connect.html.haml, spec/controllers/users/cve_spec.rb
https://github.com/omniauth/omniauth/wiki/Resolving-CVE-2015-9284
=> fix: Resolving CVE 2015 9284

app/controllers/homepages_controller.rb, app/controllers/job_offers_controller.rb, app/views/homepages/_job_offer_search_form.html.haml, app/views/job_offers/_filter.html.haml, app/views/job_offers/_filters.html.haml, config/locales/fr.yml, spec/views/job_offers/index.html.haml_spec.rb
fix #762
fix #763
fix #764
fix #765
fix #225
=> feat: add new job offer filters

app/controllers/admin/settings/organizations_controller.rb, app/javascript/css/application.scss, app/models/organization.rb, app/views/admin/settings/organizations/_form.html.haml, app/views/homepages/_hero.html.haml, app/views/homepages/_testimony.html.haml, app/views/homepages/show.html.haml, config/locales/fr.yml, config/locales/simple_form.fr.yml, db/migrate/20210226140234_add_testimony_to_organization.rb, db/schema.rb
=> feat: show testimony on homepage

app/controllers/concerns/job_offer_state_actions.rb, app/inputs/trix_editor_custom_input.rb, app/javascript/controllers/trix_editor_controller.js, app/javascript/packs/admin-bundle.js, app/models/concerns/html_length_validator.rb, app/models/job_offer.rb, app/views/admin/job_offers/_form.html.haml, config/locales/fr.yml, spec/models/job_offer_spec.rb
Allow job offer to be drafted even if descriptions are too long
fix #441
=> feat: refuse job offer with too long descriptions

app/controllers/job_offers_controller.rb, app/javascript/controllers/auto_submit_controller.js, app/javascript/controllers/scroll_controller.js, app/javascript/controllers/subcheckbox_controller.js, app/javascript/css/application.scss, app/javascript/js/rf-accordion-constants.js, app/javascript/js/rf-accordions-group.js, app/models/category.rb, app/models/job_offer.rb, app/views/job_offers/_filter.html.haml, app/views/job_offers/_filter_categories.html.haml, app/views/job_offers/_filter_regions.html.haml, app/views/job_offers/_filters.html.haml, app/views/job_offers/_job_offer.html.haml, app/views/job_offers/index.html.haml, config/locales/fr.yml, config/webpack/development.js, lib/renderers/rf_renderer.rb, sync_with_staging.sh
=> feat: allow filter to be multi selected

app/controllers/admin/job_offers_controller.rb, app/controllers/admin/settings/administrators_controller.rb, app/models/ability.rb, app/models/administrator.rb, app/models/job_application.rb, app/models/job_offer.rb, app/views/admin/job_offers/_job_offer.html.haml, app/views/admin/job_offers/_job_offer_nav.html.haml, app/views/admin/job_offers/new_transfer.html.haml, app/views/admin/settings/administrators/edit.html.haml, config/locales/fr.yml, config/routes.rb
=> Remove right on a administrator

app/views/admin/job_applications/cvlm.html.haml, app/views/admin/users/show.html.haml
=> feat: show CV and LM in pool candidate

app/javascript/css/admin.scss, app/views/admin/job_offers/_search.html.haml, config/locales/fr.yml
fix https://github.com/betagouv/civilsdeladefense/issues/361
=> Sticky search

app/controllers/admin/job_offers_controller.rb, app/controllers/homepages_controller.rb, app/models/job_offer.rb, app/views/admin/job_offers/_job_offer.html.haml, app/views/admin/job_offers/_navbar.html.haml, app/views/admin/job_offers/featured.html.haml, app/views/homepages/_job_offer_headlines.html.haml, config/locales/fr.yml, config/routes.rb, db/migrate/20210511143219_add_featured_to_job_offer.rb, db/schema.rb, spec/factories/job_offers.rb, spec/models/job_offer_spec.rb
=> feat: let admin handle feature job_offer

app/controllers/homepages_controller.rb, app/controllers/users/registrations_controller.rb, app/models/page.rb, app/views/devise/registrations/success.html.erb, app/views/job_offers/successful.html.haml, config/routes.rb, spec/controllers/users/registrations_controller_spec.rb
=> feat: add style to message when user signup

app/controllers/admin/job_offers_controller.rb, app/controllers/admin/settings/job_application_file_types_controller.rb, app/controllers/job_offers_controller.rb, app/models/job_application.rb, app/models/job_application_file_type.rb, app/models/job_offer.rb, app/views/admin/job_offers/_form.html.haml, app/views/admin/settings/inherited_resources/_form.html.haml, app/views/admin/users/_filter_category.html.haml, app/views/admin/users/_filter_spontaneous.html.haml, app/views/admin/users/_search.html.haml, app/views/job_applications/_form.html.haml, app/views/shared/_header.html.haml, config/locales/fr.yml, config/locales/simple_form.fr.yml, db/migrate/20210524140135_add_spontaneous_to_job_offer.rb, db/schema.rb, spec/factories/job_application_file_types.rb, spec/factories/job_applications.rb, spec/factories/job_offers.rb, spec/models/job_application_file_type_spec.rb, spec/models/job_application_spec.rb, spec/models/job_offer_spec.rb
fix #956
fix #958
fix #959
fix #960
fix #961
fix #962
=> feat: allow special usecas for spontaneous applications

app/helpers/job_offers_helper.rb, app/views/job_offers/_job_offer_head.html.haml, config/locales/fr.yml
=> feat: show if remote is possible on job

app/models/job_offer.rb, config/locales/fr.yml, spec/models/job_offer_spec.rb
=> feat: title witouth brackets

app/models/user.rb, app/views/admin/users/_filter_category.html.haml, app/views/admin/users/_filter_concerned.html.haml, app/views/job_applications/_form.html.haml
=> feat: fill category for job offer

app/controllers/admin/job_offer_terms_controller.rb, app/controllers/admin/job_offers_controller.rb, app/controllers/admin/settings/job_offer_terms_controller.rb, app/controllers/admin/settings/organizations_controller.rb, app/javascript/controllers/job_offer_term_controller.js, app/models/job_offer_term.rb, app/models/organization.rb, app/views/admin/job_offer_terms/index.html.haml, app/views/admin/job_offers/_job_offer.html.haml, app/views/admin/job_offers/index.html.haml, app/views/admin/settings/organizations/_form.html.haml, app/views/admin/settings/shared/_navbar.html.haml, config/locales/fr.yml, config/locales/simple_form.fr.yml, config/routes.rb, db/migrate/20210712094907_create_job_offer_terms.rb, db/schema.rb, db/seeds.rb, spec/factories/job_offer_terms.rb, spec/fixtures/organizations.yml, spec/models/organization_spec.rb, spec/routing/admin/job_offers_routing_spec.rb
=> feat: add page to be sure that admin can create job_offer fix #1050

app/mailers/applicant_notifications_mailer.rb, app/mailers/deactivation_mailer.rb, app/models/administrator.rb, app/models/concerns/deactivation_flow.rb, app/models/concerns/deletion_flow.rb, app/models/organization.rb, app/views/applicant_notifications_mailer/notice_period_before_deletion.html.erb, app/views/deactivation_mailer/notice.html.erb, app/views/deactivation_mailer/period_before.html.erb, clock.rb, db/migrate/20210623140253_add_marked_for_deactivation_on_to_administrator.rb, db/schema.rb, spec/factories/administrators.rb, spec/models/administrator_spec.rb, spec/models/user_spec.rb
=> feat: deactivate admin after x days of inactivity

app/javascript/css/admin.scss, app/javascript/js/timeout-alert.js, app/javascript/packs/admin-bundle.js, app/models/administrator.rb, config/routes.rb
=> feat: show alert beforme signout user

app/controllers/account/job_application_files_controller.rb, app/helpers/users_helper.rb, app/javascript/css/application.scss, app/views/account/job_application_files/_file_name_upload.html.haml
=> fix: document need validation if change

app/controllers/admin/settings/organizations_controller.rb, app/javascript/css/admin.scss, app/models/administrator.rb, app/views/admin/settings/organizations/_form_security.html.haml, config/locales/fr.yml, config/locales/simple_form.fr.yml, spec/models/administrator_spec.rb
=> feat: handle multiples domain for suffix

app/views/job_applications/_form.html.haml, config/locales/fr.yml
=> feat: use brand name for corporate label

docker-compose.yml, package.json
- chore: specify node version
- chore: remove old env variables
=> clean project

spec/models/profile_spec.rb
As data is not wiped after the spec has been runned, avoid creating a
model in a before all.
=> Don't create a model in a before all

app/controllers/admin/users_controller.rb, spec/requests/admin/users_controller_spec.rb
=> Redirect to admin users after user deletion

app/controllers/admin/job_offers_controller.rb, app/controllers/admin/users_controller.rb, app/javascript/controllers/selectall_controller.js, app/views/admin/job_offers/_job_offer.html.haml, app/views/admin/job_offers/index.html.haml, app/views/admin/users/_user.html.haml, app/views/admin/users/index.html.haml, spec/requests/admin/job_offers_spec.rb, spec/requests/admin/users_spec.rb, spec/views/admin/job_offers/index.html.haml_spec.rb
Closes #1271
Pages :
- admin/users
- admin/job_offers
=> feat: "Select all" disables and checks all results

app/models/job_offer.rb, spec/models/job_offer_spec.rb, spec/rails_helper.rb
=> Archive a draft job offer

app/controllers/admin/emails_controller.rb, app/controllers/admin/job_offers/readings_controller.rb, app/models/email.rb, app/models/job_application.rb, app/models/job_application/readable.rb, app/views/admin/job_offers/_job_offer.html.haml, config/locales/fr.yml, config/routes.rb, spec/factories/job_applications.rb, spec/models/email_spec.rb, spec/models/job_application/readable_spec.rb, spec/models/user_spec.rb, spec/requests/admin/job_offers/readings_spec.rb
=> feat: add 'mark as read' menu item for job offers

app/views/admin/job_offers/_filter_job_applications_count.html.haml, app/views/admin/job_offers/_search.html.haml, app/views/admin/job_offers/index.html.haml, config/locales/simple_form.fr.yml
closes #1291 
On commence par ajouter un lien "Candidatures" pour trier par nombre de candidatures : 
Ensuite, on ajoute un filtre sur la présence de candidatures :
=> feat: filter on job applications

app/controllers/job_offers_controller.rb, db/seeds.rb, spec/requests/job_offers_spec.rb
Fixes: 
https://sentry.incubateur.net/organizations/betagouv/issues/3242/?query=is%3Aresolved&statsPeriod=14d
https://sentry.incubateur.net/organizations/betagouv/issues/3243/?query=is%3Aresolved&statsPeriod=14d
=> fix bad search params

app/javascript/controllers/auto_submit_controller.js, app/javascript/controllers/autocomplete_city_controller.js, app/javascript/controllers/duplicator_controller.js, app/javascript/controllers/file_drop_controller.js, app/javascript/controllers/job_offer_management_controller.js, app/javascript/controllers/job_offer_term_controller.js, app/javascript/controllers/reset_form_controller.js, app/javascript/controllers/rf_accordions_management_controller.js, app/javascript/controllers/rf_tab_management_controller.js, app/javascript/controllers/scroll_controller.js, app/javascript/controllers/selectall_controller.js, app/javascript/controllers/spinner_controller.js, app/javascript/controllers/subcheckbox_controller.js, app/javascript/controllers/trix_editor_controller.js, app/javascript/controllers/zip_file_polling_controller.js, app/javascript/packs/admin-bundle.js, app/javascript/packs/bundle.js, package.json, yarn.lock
Upgrade stimulus to be able to use action params
=> upgrade stimulus to 3.0.1

spec/models/page_spec.rb, spec/support/controller_macros.rb, spec/views/account/emails/index.html.haml_spec.rb, spec/views/admin/job_applications/edit.html.haml_spec.rb, spec/views/admin/job_applications/index.html.haml_spec.rb, spec/views/admin/job_applications/show.html.haml_spec.rb, spec/views/admin/job_offers/archived.html.haml_spec.rb, spec/views/admin/job_offers/edit.html.haml_spec.rb, spec/views/admin/job_offers/index.html.haml_spec.rb, spec/views/admin/job_offers/new.html.haml_spec.rb, spec/views/admin/job_offers/show.html.haml_spec.rb, spec/views/admin/settings/categories/edit.html.haml_spec.rb, spec/views/admin/settings/categories/index.html.haml_spec.rb, spec/views/admin/settings/categories/new.html.haml_spec.rb, spec/views/admin/settings/employers/edit.html.haml_spec.rb, spec/views/admin/settings/employers/index.html.haml_spec.rb, spec/views/admin/settings/employers/new.html.haml_spec.rb, spec/views/job_offers/index.html.haml_spec.rb, spec/views/job_offers/show.html.haml_spec.rb
@btrd j'ai entrepris (ici #1290) de mettre à jour Rubocop, et les conventions de style du projet, pour aller vers quelque chose de plus moderne. 
Au fur et à mesure que j'avance, je m'aperçois que ça va faire beaucoup de changements d'un coup. Je te propose donc de faire une PR de temps en temps, qui adresse un seul sujet à chaque fois. Ici, on fixe les offenses `RSpec/HookArgument`. Je trouve cette approche plus digeste et moins risquée. Est-ce que tu es ok ?
Quand toutes les offenses auront été fixées, je ferai la PR pour upgrade Rubocop pour de vrai.
=> fix RSpec/HookArgument

app/controllers/admin/settings/administrators_controller.rb, app/views/admin/settings/administrators/index.html.haml
Closes #1324
On pagine la page des administrateurs pour améliorer ses performances :
=> feat: paginate admins index

spec/factories/administrators.rb, spec/requests/admin/accounts_spec.rb, spec/requests/admin/job_offers_spec.rb, spec/requests/admin/preferred_users_lists_spec.rb, spec/requests/admin/recipients_spec.rb, spec/requests/admin/users_spec.rb
=> spec: cover admin::accounts

spec/factories/users.rb, spec/requests/account/users_spec.rb
=> specs: cover account::user

spec/requests/account/job_applications_spec.rb
=> spec: cover account::job_applications

app/controllers/admin/users_controller.rb, spec/controllers/admin/users_controller_spec.rb, spec/factories/users.rb, spec/requests/admin/users_spec.rb
=> spec: cover admin::users

app/controllers/admin/settings/administrators_controller.rb, app/views/admin/settings/administrators/index.html.haml, spec/requests/admin/settings/administrators_spec.rb
fixes https://sentry.incubateur.net/organizations/betagouv/issues/4791/?project=47&query=is%3Aunresolved
=> fix: inactive admins list

app/models/job_application.rb, app/models/job_application_file.rb, db/migrate/20220701133357_add_unique_index_to_job_application_files.rb, db/migrate/20220701133604_add_unique_index_to_job_applications.rb, db/schema.rb, spec/factories/job_application_files.rb, spec/factories/job_applications.rb, spec/models/job_application_spec.rb
fixes https://sentry.incubateur.net/organizations/betagouv/issues/4814/?project=47&query=is%3Aunresolved+is%3Afor_review+assigned_or_suggested%3A%5Bme%2C+none%5D&sort=inbox
=> fix duplicate migrations

spec/requests/admin/job_application_files_spec.rb
=> spec: cover admin::job_application_file

spec/requests/admin/preferred_users_spec.rb
=> spec: cover admin preferred users

spec/requests/pages_spec.rb
=> spec: cover pages

spec/requests/account/job_application_files_spec.rb
=> spec: account job application files

spec/requests/admin/preferred_users_lists_spec.rb
=> spec: cover admin::preferred users list

spec/requests/admin/email_templates_spec.rb
=> spec: cover admin::email templates

spec/factories/salary_ranges.rb, spec/requests/admin/salary_ranges_spec.rb
=> spec: cover admin::salary ranges

app/controllers/admin/stats/recruitments_controller.rb, config/locales/fr.yml, config/routes.rb, lib/services/exporter/stat_job_offers.rb, spec/requests/admin/stats/job_applications_spec.rb, spec/requests/admin/stats/job_offers_spec.rb
=> spec: cover admin::stats

app/views/admin/settings/inherited_resources/_element.html.haml, app/views/admin/settings/inherited_resources/_table.html.haml, config/locales/fr.yml, spec/factories/organization_defaults.rb, spec/requests/admin/settings/organization_defaults_spec.rb
=> specs: cover admin::settings::organization_defaults

spec/requests/admin/settings/organizations_spec.rb
=> spec: cover admin::settings::organizations

spec/requests/admin/settings/salary_ranges_spec.rb, spec/requests/robots_spec.rb, spec/requests/sitemaps_spec.rb, spec/support/shared_examples/admin_setting.rb
=> spec: cover robots & sitemaps

app/controllers/admin/emails_controller.rb, spec/requests/admin/emails_spec.rb
=> spec: cover admin::emails

app/controllers/admin/settings/administrators_controller.rb, spec/factories/administrators.rb, spec/requests/admin/settings/administrators_spec.rb
=> spec: cover admin:administrators

app/controllers/admin/users_controller.rb, spec/requests/admin/users_spec.rb
see https://sentry.incubateur.net/organizations/betagouv/issues/4983/?project=47
=> fix: multi_select crash when no list is provided

Gemfile, Gemfile.lock, app/controllers/admin/base_controller.rb, app/controllers/application_controller.rb, app/controllers/concerns/turbo/redirection.rb, app/javascript/js/reload-with-turbo.js, app/javascript/js/timeout-alert.js, app/javascript/packs/admin-bundle.js, app/views/admin/job_applications/change_state.js.erb, app/views/admin/job_applications/update.js.erb, app/views/admin/job_offer_terms/index.html.haml, app/views/admin/job_offers/index.js.erb, app/views/admin/preferred_users_lists/show.html.haml, app/views/admin/users/index.html.haml, app/views/layouts/admin.html.haml, package.json, yarn.lock
=> upgrade: replace turbolinks with turbo

app/javascript/css/admin.scss
=> :lipstick: admin: move scroll-to-top button to the right side

app/controllers/concerns/job_offer_state_actions.rb, app/models/job_offer.rb, app/views/admin/job_offers/state_unchanged.js.erb, config/locales/fr.yml, spec/factories/job_offers.rb, spec/models/job_offer_spec.rb, spec/requests/admin/job_offers_spec.rb
=> feat: org description is required for publishing

app/views/job_applications/_form.html.haml
=> :adhesive_bandage: remove usless spinner

app/controllers/admin/settings/organizations_controller.rb, app/models/organization.rb, app/models/profile.rb, app/views/admin/settings/organizations/_form.html.haml, app/views/layouts/application.html.haml, config/locales/simple_form.fr.yml, db/migrate/20220826140104_remove_tracking_attributes_from_organization.rb, db/schema.rb, spec/factories/profiles.rb, spec/fixtures/organizations.yml, spec/models/organization_spec.rb, spec/models/profile_spec.rb
=> :fire: remove useless trackers

app/helpers/admin/job_applications_helper.rb, app/javascript/controllers/rich_tooltip_controller.js, app/javascript/css/admin.scss, app/views/admin/users/_user.html.haml, package.json, yarn.lock
closes #846 
Add a small "document" icon to show a preview of the last resume in a tooltip :
=> :sparkles: show resumes in tooltip

app/views/shared/_trackers.html.erb
Remove ATinternet tracker script
=> Remove ATinternet tracker script

scalingo.json
=> ⬆️ upgrade scaligo stack to 20

lib/renderers/rf_renderer.rb
=> Fix pagination

config/webpack/environment.js, package.json, yarn.lock
Pour continuer à supprimer les vulnérabilités connues des dépendances du projet, on met à jour plusieurs librairies front-end.
=> :arrow_up: Upgrade various front libs

app/models/concerns/securable.rb
Sometimes a PDF file is not convertable in image.
=> 🐛 Fix unconvertable pdf files

app/views/admin/emails/_email.html.haml
https://sentry.incubateur.net/organizations/betagouv/issues/47809/?project=47&query=is%3Aunresolved&referrer=issue-stream
=> 🐛 Fix nil attachment content

app/models/concerns/securable.rb
https://sentry.incubateur.net/organizations/betagouv/issues/52860/?query=is%3Aunresolved+is%3Afor_review+assigned_or_suggested%3A%5Bme%2C+none%5D&referrer=issue-stream&sort=inbox&statsPeriod=14d
=> 🐛 Don't trigger callbacks when securing content
