app/controllers/admin/job_offers_controller.rb
Ajout de la route. + fonctionnalité dans le controler
Au départ je voulait faire ça : 
`if @job_offer.save && @job_offer.publish` à la ligne 52
j'ai aussi voulu faire avant le save:
`@job_offer.state = @job_offer.state.published` à la ligne 50
Mais ça ne fonctionne pas (l'offre rester en brouillon) alors j'ai estimé que lors de l'ajout d'une offre il est forcément "draf" et je la modifie en published pendant la validation.
=> Impossible de créer une annonce directement au statut publié Fix/34

app/controllers/job_offers_controller.rb, app/views/devise/shared/_france_connect.html.haml, app/views/job_applications/_form.html.haml, app/views/job_offers/_job_offer_content.html.haml, config/routes.rb, spec/requests/job_offers_spec.rb
fix #431
FranceConnect (in production only) need a fix url to enable CORS request so I move from /job_offers/:id/apply to /job_offers/apply?id=:id
=> feat: enable FranceConnect on apply page

app/controllers/admin/preferred_users_controller.rb, app/views/admin/preferred_users_lists/_user.html.haml, app/views/admin/preferred_users_lists/show.html.haml, app/views/admin/users/_user.html.haml, config/locales/fr.yml, config/routes.rb, spec/factories/preferred_users.rb, spec/requests/admin/preferred_users_spec.rb
Closes #1127
On améliore un peu la card qui représente une candidature dans une liste, afin de : 
1. rendre plus explicite l'action qui mène à l'écran des listes dans laquelle cette candidature est incluse, en renommant "Mon vivier" en "Listes"
2. retirer directement une candidature de la liste courante
=> feat: remove preferred user from list

app/controllers/admin/users_controller.rb, app/models/concerns/deletion_flow.rb, app/models/user.rb, spec/models/user_spec.rb
see #1279
Lorsqu'on supprime un·e user, ses emails et documents sont également supprimés. On en profite pour recalculer le nombre de notifications pour l'administrateur·rice, afin d'avoir un compte à jour.
=> recompute notifications count when deleting user

app/jobs/zip_job_application_files_job.rb, spec/jobs/zip_job_application_files_job_spec.rb
When a file can't be read (for example it is unreachable, empty or corrupted), it raises a "NoMethodError: undefined method `body' for nil:NilClass".
We catch it to skip the file in the zip archive.
Related to: https://sentry.incubateur.net/organizations/betagouv/issues/2981/?project=47&query=is%3Aunresolved
=> fix: unreadable file

app/controllers/admin/multiple_recipients_emails_controller.rb, app/javascript/css/admin.scss, app/javascript/js/email-template-select-handling.js, app/models/job_application.rb, app/models/multiple_recipients_email.rb, app/views/admin/job_offers/_board_column.html.haml, app/views/admin/multiple_recipients_emails/new.html.haml, config/locales/fr.yml, config/routes.rb, db/seeds.rb, spec/factories/job_offers.rb, spec/factories/users.rb, spec/models/multiple_recipients_email_spec.rb, spec/requests/admin/multiple_recipients_emails_spec.rb
closes #1280 
On ajoute un écran pour envoyer simultanément un email à toutes les personnes d'une colonne donnée.
À cause du manque d'espace disponible, la fonctionnalité est disponible sous forme d'icône et le titre s'affiche en tooltip : 
À ce stade, les destinataires sont ceux de la colonne concernée :
=> feat: multi recipients email

app/controllers/concerns/sentry_identifier.rb
or it won't be set when the request crashes
=> set sentry user before action

app/controllers/admin/recipients_controller.rb, app/javascript/controllers/add_recipient_controller.js, app/javascript/controllers/autocomplete_city_controller.js, app/javascript/controllers/remove_recipient_controller.js, app/javascript/css/autocomplete.scss, app/javascript/packs/admin-style.js, app/models/job_application.rb, app/models/recipient.rb, app/views/admin/job_offers/_form.html.haml, app/views/admin/multiple_recipients_emails/_job_application_id.html.haml, app/views/admin/multiple_recipients_emails/_recipient.html.haml, app/views/admin/multiple_recipients_emails/_recipients.html.haml, app/views/admin/multiple_recipients_emails/new.html.haml, app/views/admin/recipients/create.js.erb, config/routes.rb, package.json, spec/models/recipient_spec.rb, spec/requests/admin/recipients_spec.rb, yarn.lock
closes #1294
On commence par ajouter la nouvelle version de la libraire `algolia/autocomplete-js`, destinée à remplacer celle du projet (`autocomplete.js`).
Ensuite, on permet la suppression, puis l'ajout, de destinataires : 
Enfin, sur l'écran de création de `JobOffer`, on remplace `autocomplete.js` par `algolia/autocomplete-js` :
=> feat: add and remove recipients

app/jobs/zip_job_application_files_job.rb, spec/jobs/zip_job_application_files_job_spec.rb
See https://sentry.incubateur.net/organizations/betagouv/issues/2995/?project=47&query=is%3Aunresolved+is%3Afor_review+assigned_or_suggested%3A%5Bme%2C+none%5D&sort=inbox
=> fix: don't crash when the ZipFile already exists

app/controllers/admin/settings/administrators_controller.rb, app/models/administrator.rb, spec/models/administrator_spec.rb
See https://sentry.incubateur.net/organizations/betagouv/issues/3489/?project=47&query=is%3Aunresolved+is%3Afor_review+assigned_or_suggested%3A%5Bme%2C+none%5D&sort=inbox
The transfer to a new admin used to crash when the email was invalid,
because of a `save!`.
Here we manage this case smoothly.
=> fix: transfer to a new admin with invalid email

app/controllers/domain_validations_controller.rb, app/views/domain_validations/show.text.erb, config/routes.rb, spec/requests/domain_validations_spec.rb
Afin de valider un nom de domaine, on retourne sous forme de plain text le contenu d'une variable d'environnement préfixée par `DOMAIN_VALIDATION_`.
=> feat: validate a domain

app/controllers/application_controller.rb, app/controllers/concerns/timeoutable.rb, app/javascript/controllers/timeoutable_controller.js, app/models/administrator.rb, app/models/user.rb, app/views/layouts/application.html.haml, app/views/shared/_timeout.html.haml, config/initializers/devise.rb
Closes #1067 
On rend la session utilisateur timeoutable (comme pour l'admin), avec une durée de session de 1h.
5 minutes avant la fin de la session, on affiche une alerte :
=> feat: user is timeoutable

app/views/admin/users/index.html.haml
Should fix this double request when searching (full text) for candidates:
=> optim: avoid requesting twice the DB

app/views/admin/stats/job_applications/_search.html.haml, app/views/admin/users/_search.html.haml, config/locales/simple_form.fr.yml
closes #1087
Sur les deux écrans concernés (vivier et statistiques), on établit la largeur et la position des filtres en fonction de la largeur de l'écran. On réduit également un peu la longueur des wordings, pour que ça rentre mieux.
=> feat: improve filters UI

app/controllers/admin/archives_controller.rb, app/controllers/admin/settings/archiving_reasons_controller.rb, app/javascript/packs/admin-bundle.js, app/models/archiving_reason.rb, app/models/job_offer.rb, app/views/admin/archives/_form.html.haml, app/views/admin/archives/create.js.erb, app/views/admin/archives/new.js.erb, app/views/admin/job_offers/_job_offer.html.haml, app/views/admin/settings/shared/_navbar.html.haml, app/views/layouts/admin.html.haml, app/views/shared/_modal.html.haml, config/locales/fr.yml, config/locales/simple_form.fr.yml, config/routes.rb, db/migrate/20220706084116_create_archiving_reasons.rb, db/migrate/20220706090806_add_archiving_reason_to_job_offers.rb, db/schema.rb, spec/factories/archiving_reasons.rb, spec/factories/job_offers.rb, spec/models/archiving_reason_spec.rb, spec/models/job_offer_spec.rb, spec/requests/admin/archives_spec.rb, spec/requests/admin/settings/archiving_reasons_spec.rb
closes #444 
On ajoute un motif lors de l'archivage d'une annonce.
Pour cela, on commence par ajouter les motifs d'archivage dans les paramètres :
Puis, au moment d'archiver l'annonce, une modale permet de choisir le motif : 
La raison est alors visible dans le cartouche de l'offre :
=> feat: job offer's archiving reason

app/controllers/admin/stats/job_applications_controller.rb, app/controllers/admin/stats/job_offers_controller.rb, app/jobs/warm_up_job_applications_stats_cache_job.rb, app/models/job_application.rb, clock.rb, spec/jobs/warm_up_job_applications_stats_cache_job_spec.rb
Store the heaviest query in cache for to avoid 10+s total request duration, and warm up the cache periodically for the most common dates combinations.
closes #1325
=> :zap: stats: cache the job applications stats for 24h

app/views/job_applications/_form.html.haml
When a required attribute isn't provided, when submitting a job application, the button was replaced by a spinner and never came back to normal state.
=> :ambulance: fix unability to submit job application

app/inputs/trix_editor_custom_input.rb, app/javascript/controllers/autocomplete_city_controller.js, app/javascript/controllers/form_save_controller.js, app/views/admin/job_offers/_form.html.haml, app/views/job_applications/_form.html.haml
closes #850
On ajoute la sauvegarde automatique des formulaires suivants : 
- côté admin : la création d'un nouveau job offert
- côté user : la création d'un nouveau job application, c'est à dire le fait de postuler à une offre
Le comportement est donc le suivant :
1. la personne commence à remplir le formulaire
2. elle quitte pour une raison ou une autre (fermeture du navigateur ou de l'onglet, expiration de la session, bouton précédent...)
3. lorsqu'elle revient sur le formulaire, les champs sont remplis avec sa saisie précédente
4. lorsqu'elle soumet le formulaire, la sauvegarde de sa saisie précédente est effacée
Les limites sont les suivantes : 
- les champs de type fichier ne peuvent être sauvegardés, ils ne sont plus accessibles après avoir quitté le formulaire
- les mots de passe …
=> :sparkles: auto save job offer and job application forms

app/controllers/admin/stats/job_applications_controller.rb
Default start and end dates should match the cache warming.
=> :adhesive_bandage: harmonize job application stats start date

app/javascript/controllers/files_upload_controller.js, app/javascript/controllers/rf_tab_management_controller.js, app/models/email.rb, app/views/account/emails/_form.html.haml, app/views/admin/emails/_form.html.haml, app/views/admin/multiple_recipients_emails/new.html.haml, config/locales/fr.yml
For each email form, allow to:
- add one or multiple files to file input
- remove added files
closes #1029
=> :children_crossing: individually manage email attachments

lib/services/process_inbound_message.rb, spec/lib/process_inbound_message_spec.rb
D'après #1409, les emails envoyés par les candidat·es ne sont pas créés dans la messagerie de CVD.
Parallèlement, [cette erreur Sentry](https://sentry.incubateur.net/organizations/betagouv/issues/21030/events/09a90eb7572e40c4b641f5972f3f12f6/?project=47&query=is%3Aunresolved) indique que la création d'emails échoue parce que l'email subject est manquant.
Afin de corriger ce bug, on utilise ici un subject par défaut si jamais celui-ci est manquant.
=> Fix: create email when subject is blank

app/helpers/job_offers_helper.rb, app/views/account/job_applications/_job_application.html.haml, app/views/admin/job_offers/_job_offer.html.haml, app/views/homepages/_job_offer_headline_card.html.haml, app/views/job_offers/_job_offer.html.haml, app/views/job_offers/index.json.jbuilder, lib/services/exporter/job_offer.rb, lib/services/exporter/job_offers.rb, spec/factories/job_offers.rb, spec/helpers/job_offers_helper_spec.rb
On a rencontré plusieurs crash en prod : 
https://sentry.incubateur.net/organizations/betagouv/issues/26336/?project=47&query=is%3Aunresolved+is%3Afor_review+assigned_or_suggested%3A%5Bme%2C+none%5D&sort=inbox
https://sentry.incubateur.net/organizations/betagouv/issues/26330/?project=47&query=is%3Aunresolved+is%3Afor_review+assigned_or_suggested%3A%5Bme%2C+none%5D&sort=inbox
https://sentry.incubateur.net/organizations/betagouv/issues/26329/?project=47&query=is%3Aunresolved+is%3Afor_review+assigned_or_suggested%3A%5Bme%2C+none%5D&sort=inbox
Dans tous les cas le problème est le même : le `contract_type` a disparu et ce n'est pas correctement géré par l'application. C'est pourtant une fonctionnalité tout à fait possible, puisqu'on peut supprimer un contract type dans les paramètres de …
=> 🐛 Fix crashes when contract type is nil

app/models/admin_email.rb, app/models/daily_summary.rb, db/migrate/20230420144305_create_admin_emails.rb, db/schema.rb
Dans le but de débugger #1474, on conserve en BDD la trace des emails envoyés aux administrateur·rices.
=> Track emails sent to administrators

.buildpacks, Aptfile
On vérifie en amont de https://github.com/betagouv/civilsdeladefense/pull/1498 qu'il est possible d'exécuter pdftoppm (poppler-utils) et img2pdf en environnement de production.
=> :heavy_plus_sign: Add pdf and img dependencies

app/models/concerns/securable.rb
Sometimes getting the content_type of a file throws an error, because the file is not there or not readable from Outscale. It may occur for old files / unstable content.
That's because:
=> :bug: Fix undefined body error

app/models/concerns/securable.rb
When the original content filename contains special chars, downloading the file may fails.
We fix it by parameterizing the filename.
=> 🐛 Fix original content download

app/models/concerns/securable.rb, spec/models/concerns/securable_spec.rb
Define the `DELIVER_SECURED_CONTENT` in order to deliver secured content.
Unset it to deliver regular content.
(content is the content of PDF file, see #1502)
=> 🚸 Deliver secured content only when env var is set

app/javascript/css/_job_offer_content.scss, app/javascript/css/application.scss, app/views/job_offers/_job_offer_content.html.haml
Comme décrit dans #1489, le style des listes à puces ne s'affiche pas, sur les instances de staging / production uniquement (c'est ok en local). C'est vraisemblablement une conséquence de la version du DSFR qui est incluse dans le projet.
Ici, on reconstruit les styles de ul / ol pour les job offers.
closes #1489
=> :bug: Fix ul / ol style on job offer content

app/models/concerns/suspendable.rb, config/locales/devise.fr.yml, spec/models/concerns/suspendable_spec.rb
On met à jour le message qui s'affiche lorsqu'un compte est suspendu.
closes #1507
=> 💬 Update wording for suspended user

app/jobs/secure_content_job.rb, app/models/concerns/securable.rb, lib/pdf_utils.rb, lib/tasks/migrate_data/secure_contents.rake
Pour résoudre les problèmes relevés dans les documents PDF sécurisés, on apporte plusieurs modification dans le processus de sécurisation.
Cette PR règle :
- le problème d'absence de visibilité du contenu (PDF qui sortaient en noir)
- le problème de la taille des fichiers (qui passaient de quelques centaines de Ko à plusieurs Mo)
- le problème de qualité / lisibilité variable à cause de la densité (elle est désormais à 150 et la qualité des fichiers semble bonne)
closes #1541
=> Improve secured PDF file quality
